import type { NextPage } from "next";
import Head from "next/head";
import Spline from "@splinetool/react-spline";
import { useState } from "react";
import { IoMenu } from "react-icons/io5";

const Home: NextPage = () => {
  const [isActive, setIsActive] = useState(false);

  return (
    <div className="flex w-screen h-screen min-h-screen flex-col items-center justify-center relative bg-primary pb-20">
      <Head>
        <meta
          name="google-site-verification"
          content="TIUrkchOlm9fPiQ_hEfy-3--R5cBqUlVtCsHjhS6tkI"
        />

        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navigation Bar*/}
      <nav className="w-full px-6 z-50 fixed insert-x-0 top-2 flex justify-center items-center">
        <div className="w-full md:w-880 p-4 rounded-2xl flex items-center bg-navBar">
          <p className="text-lg text-slate-200 font-medium">
            Natnael Gebremichael
          </p>
          <div className="hidden md:flex items-center gap-6 ml-6 flex-1">
            <a
              href="#home"
              className="tetxt-base text-textBase font-medium hover:text-slate-100 cursor-pointer duration-100 ease-in-out"
            >
              {" "}
              Home
            </a>
            <a
              href="#About"
              className="tetxt-base text-textBase font-medium hover:text-slate-100 cursor-pointer duration-100 ease-in-out"
            >
              {" "}
              About
            </a>
            <a
              href="#Projects"
              className="tetxt-base text-textBase font-medium hover:text-slate-100 cursor-pointer duration-100 ease-in-out"
            >
              {" "}
              Projects
            </a>
            <a
              href="#Contacts"
              className="tetxt-base text-textBase font-medium hover:text-slate-100 cursor-pointer duration-100 ease-in-out"
            >
              {" "}
              Contacts
            </a>
            <a
              href="#"
              className="ml-auto text-base text-textBase font-medium hover:text-slate-100 cursor-pointer border border-textBase px-2 py-1
              rounded-xl hover:border-gray-100 duration-100 ease-in-out"
            >
              Download
            </a>
          </div>
          <div
            className="block md:hidden ml-auto cursor-pointer"
            onClick={() => setIsActive(!isActive)}
          >
            <IoMenu className="text-2xl text-textBase" />
          </div>

          {isActive && (
            <div
              className="p-4 w-275 bg-navBar rounded-lg fixed top-24 right-16 flex flex-col items-center 
            justify-evenly gap-6"
            >
              <a
                href="#home"
                className="tetxt-base text-textBase font-medium hover:text-slate-100 cursor-pointer duration-100 ease-in-out"
                onClick={() => setIsActive(false)}
              >
                {" "}
                Home
              </a>
              <a
                href="#About"
                className="tetxt-base text-textBase font-medium hover:text-slate-100 cursor-pointer duration-100 ease-in-out"
                onClick={() => setIsActive(false)}
              >
                {" "}
                About
              </a>
              <a
                href="#Projects"
                className="tetxt-base text-textBase font-medium hover:text-slate-100 cursor-pointer duration-100 ease-in-out"
                onClick={() => setIsActive(false)}
              >
                {" "}
                Projects
              </a>
              <a
                href="#Contacts"
                className="tetxt-base text-textBase font-medium hover:text-slate-100 cursor-pointer duration-100 ease-in-out"
                onClick={() => setIsActive(false)}
              >
                {" "}
                Contacts
              </a>
              <a
                href="#"
                className="
                onClick={() => setIsActive(false)}text-base text-textBase font-medium hover:text-slate-100 cursor-pointer border border-textBase px-2 py-1
              rounded-xl hover:border-gray-100 duration-100 ease-in-out"
              onClick={() => setIsActive(false)}
              >
                Download
              </a>
            </div>
          )}
        </div>
      </nav>

      <Spline scene="https://prod.spline.design/0zePFgYYBpN7GtSq/scene.splinecode" />
      <div className="absolute bottom-10 w-full justify-center items-center flex">
         <div className="shadow-md p-4 flex items-center justify-center bg-zinc-900 rounded-3xl"> </div>
         <p className="text-white "> Press and drag to orbit </p>
         </div>

    </div>
  );
};

export default Home;
